### ISSUE TITLE
Repeated message bug

### ISSUE THREAD

**Issue by DevCallMeAJ** [Sentinel-Security/_Sentinel#4]
**Describe the bug**
This bug happens when you use a command. It will repeat the same text twice.

**To Reproduce**
1. Run s?toggle

**Expected behavior**
Depending on how many times you run the command, the message would show up as many times as you run it

**Screenshots**
https://avery.is-a-legend.xyz/06b7278.png

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit
 - Discord Build: Unknown, Edge browser

**Comment by TheCuteFoxxy** [comment]
Unable to reproduce.
